name: wfc
description: A package providing procedural map generation using the Wave Function Collapse algorithm.
version: 1.0.3
repository: https://github.com/rick-dalley/wfc
homepage: https://github.com/rick-dalley/wfc

environment:
  sdk: ^3.5.4

# Add regular dependencies here.

dependencies:
  image: ^4.5.0
  xml: ^6.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
