name: wfc
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
repository: https://github.com/rick-dalley/wfc
homepage: https://github.com/rick-dalley/wfc

environment:
  sdk: ^3.5.4

# Add regular dependencies here.

dependencies:
  image: ^3.0.1
  xml: ^6.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
